CREATE TABLE [dbo].[PortalRole]
(
	[Id] INT IDENTITY(1,1) NOT NULL,
	[Name] NVARCHAR(50) NOT NULL, 
    [Description] NVARCHAR(200) NULL,
	CONSTRAINT [PK_PortalRole] PRIMARY KEY CLUSTERED ([Id] ASC)
)
